import type { Theme } from "../types";

export const clackFrost: Theme = {
  id: "clack-frost",
  name: "Clack Frost",
  description: "High-contrast blue-gray surfaces with cyan focus.",
  editorTheme: { dark: "tokyo-night", light: "tokyo-night" },
  variants: {
    dark: {
      colors: {
        background: "#071019",
        foreground: "#eefaff",
        card: "#0d1a27",
        cardForeground: "#eefaff",
        popover: "#122234",
        popoverForeground: "#eefaff",
        primary: "#5ee7ff",
        primaryForeground: "#031018",
        secondary: "#132536",
        secondaryForeground: "#eefaff",
        muted: "#132536",
        mutedForeground: "#82a2b9",
        accent: "#193249",
        accentForeground: "#eefaff",
        destructive: "#ff6f8f",
        border: "rgba(119,218,255,0.15)",
        input: "rgba(119,218,255,0.19)",
        ring: "#5ee7ff",
        sidebar: "#06101a",
        sidebarForeground: "#b9d8e9",
        sidebarPrimary: "#5ee7ff",
        sidebarPrimaryForeground: "#031018",
        sidebarAccent: "#132536",
        sidebarAccentForeground: "#eefaff",
        sidebarBorder: "rgba(119,218,255,0.15)",
        sidebarRing: "#5ee7ff",
        radius: "0.42rem",
      },
      terminal: {
        background: "#06101a",
        foreground: "#dbf5ff",
        cursor: "#5ee7ff",
        cursorAccent: "#031018",
        selection: "rgba(94,231,255,0.24)",
        ansi: [
          "#102033",
          "#ff6f8f",
          "#54dda6",
          "#f0d976",
          "#7eb6ff",
          "#b594ff",
          "#5ee7ff",
          "#dbf5ff",
          "#6f8ea7",
          "#ff90a8",
          "#7bedbf",
          "#ffe699",
          "#a6d0ff",
          "#c7afff",
          "#8ef0ff",
          "#ffffff",
        ],
      },
    },
  },
};
